name: Scraper Boletín Oficial

on:
  workflow_dispatch:

jobs:
  test-boletin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias
        run: |
          pip install selenium pandas

      - name: Correr Test de Boletín

        run: python boletin.py
